//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARMU.Modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime HeureDebut { get; set; }
        public System.DateTime HeureFin { get; set; }
        public int Constats { get; set; }
        public string Action1 { get; set; }
        public int SuiviDemandeID { get; set; }
    
        public virtual SuiviDemande SuiviDemande { get; set; }
    }
}
