//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARMU.Modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignation
    {
        public Assignation()
        {
            this.TacheQuotidienne_Assignation = new HashSet<TacheQuotidienne_Assignation>();
        }
    
        public int DetailPlanID { get; set; }
        public int JourMoisID { get; set; }
        public int QuantitieJournee { get; set; }
        public int NbCompleteJournee { get; set; }
    
        public virtual ICollection<TacheQuotidienne_Assignation> TacheQuotidienne_Assignation { get; set; }
        public virtual DetailPlanificationMensuelle DetailPlanificationMensuelle { get; set; }
        public virtual JourMois JourMois { get; set; }
    }
}
