//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARMU.Modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemandeSpeciale
    {
        public DemandeSpeciale()
        {
            this.SuiviDemande = new HashSet<SuiviDemande>();
            this.ProblemeSouleve = new HashSet<ProblemeSouleve>();
            this.Suspect = new HashSet<Suspect>();
            this.TacheQuotidienne = new HashSet<TacheQuotidienne>();
        }
    
        public int ID { get; set; }
        public string NomDemandeur { get; set; }
        public int AdresseDemandeur { get; set; }
        public string TelephoneDemandeur { get; set; }
        public string FaxDemandeur { get; set; }
        public string CourrielDemandeur { get; set; }
        public bool DemandeRetour { get; set; }
        public string DescriptionDemande { get; set; }
        public string Localisation { get; set; }
        public string DescriptionVehicule { get; set; }
        public Nullable<int> ModeleVehiculeID { get; set; }
        public string Immatriculation { get; set; }
        public string DescriptionSuspect { get; set; }
        public Nullable<bool> SecteurContrevenant { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime DateDemande { get; set; }
        public string Provenance { get; set; }
        public string Municipalite { get; set; }
        public Nullable<int> Releve { get; set; }
        public string JourSemaine { get; set; }
    
        public virtual ModeleVehicule ModeleVehicule { get; set; }
        public virtual ICollection<SuiviDemande> SuiviDemande { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<ProblemeSouleve> ProblemeSouleve { get; set; }
        public virtual ICollection<Suspect> Suspect { get; set; }
        public virtual ICollection<TacheQuotidienne> TacheQuotidienne { get; set; }
    }
}
