//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARMU.Modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailPlanificationMensuelle
    {
        public DetailPlanificationMensuelle()
        {
            this.Assignation = new HashSet<Assignation>();
        }
    
        public int ID { get; set; }
        public int PlanificationMensuelleAnnee { get; set; }
        public int PlanificationMensuelleMois { get; set; }
        public int DomaineID { get; set; }
        public int PrioritesLocalesID { get; set; }
        public int EndroitsCiblesID { get; set; }
        public int ActionsPrevuesID { get; set; }
        public string Condition { get; set; }
        public Nullable<int> Quantite { get; set; }
        public Nullable<int> Resultat { get; set; }
    
        public virtual ActionPrevue ActionPrevue { get; set; }
        public virtual ICollection<Assignation> Assignation { get; set; }
        public virtual EndroitCible EndroitCible { get; set; }
        public virtual PrioriteLocale PrioriteLocale { get; set; }
        public virtual Domaine Domaine { get; set; }
        public virtual PlanificationMensuelle PlanificationMensuelle { get; set; }
    }
}
