//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARMU.Modele
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class garmuBDEntities : DbContext
    {
        public garmuBDEntities()
            : base("name=garmuBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Action> Action { get; set; }
        public DbSet<ActionPrevue> ActionPrevue { get; set; }
        public DbSet<Assignation> Assignation { get; set; }
        public DbSet<DemandeSpeciale> DemandeSpeciale { get; set; }
        public DbSet<DetailPlanificationMensuelle> DetailPlanificationMensuelle { get; set; }
        public DbSet<Domaine> Domaine { get; set; }
        public DbSet<Employee> Employee { get; set; }
        public DbSet<EndroitCible> EndroitCible { get; set; }
        public DbSet<Equipe> Equipe { get; set; }
        public DbSet<JourMois> JourMois { get; set; }
        public DbSet<MarqueVehicule> MarqueVehicule { get; set; }
        public DbSet<ModeleVehicule> ModeleVehicule { get; set; }
        public DbSet<Patrouilleur> Patrouilleur { get; set; }
        public DbSet<PlanificationMensuelle> PlanificationMensuelle { get; set; }
        public DbSet<PrioriteLocale> PrioriteLocale { get; set; }
        public DbSet<ProblemeSouleve> ProblemeSouleve { get; set; }
        public DbSet<Releve> Releve { get; set; }
        public DbSet<Secteur> Secteur { get; set; }
        public DbSet<SuiviDemande> SuiviDemande { get; set; }
        public DbSet<Suspect> Suspect { get; set; }
        public DbSet<TacheQuotidienne> TacheQuotidienne { get; set; }
        public DbSet<TacheQuotidienne_Assignation> TacheQuotidienne_Assignation { get; set; }
        public DbSet<Vehicule> Vehicule { get; set; }
    }
}
