//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARMU.Modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class JourMois
    {
        public JourMois()
        {
            this.Assignation = new HashSet<Assignation>();
            this.TacheQuotidienne = new HashSet<TacheQuotidienne>();
        }
    
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> NoEquipe { get; set; }
        public Nullable<int> ReleveID { get; set; }
        public Nullable<int> PlanificationMensuelleAnnee { get; set; }
        public Nullable<int> PlanificationMensuelleMois { get; set; }
    
        public virtual ICollection<Assignation> Assignation { get; set; }
        public virtual Equipe Equipe { get; set; }
        public virtual ICollection<TacheQuotidienne> TacheQuotidienne { get; set; }
        public virtual Releve Releve { get; set; }
        public virtual PlanificationMensuelle PlanificationMensuelle { get; set; }
    }
}
