//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARMU.Modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patrouilleur
    {
        public Patrouilleur()
        {
            this.SuiviDemande = new HashSet<SuiviDemande>();
            this.TacheQuotidienne = new HashSet<TacheQuotidienne>();
        }
    
        public int EmployeeID { get; set; }
        public int Matricule { get; set; }
        public Nullable<int> EquipeNoEquipe { get; set; }
        public Nullable<int> VehiculeID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Equipe Equipe { get; set; }
        public virtual Vehicule Vehicule { get; set; }
        public virtual ICollection<SuiviDemande> SuiviDemande { get; set; }
        public virtual ICollection<TacheQuotidienne> TacheQuotidienne { get; set; }
    }
}
