//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARMU.Modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanificationMensuelle
    {
        public PlanificationMensuelle()
        {
            this.DetailPlanificationMensuelle = new HashSet<DetailPlanificationMensuelle>();
            this.JourMois = new HashSet<JourMois>();
        }
    
        public int Annee { get; set; }
        public int Mois { get; set; }
        public string Theme { get; set; }
        public string Poste { get; set; }
    
        public virtual ICollection<DetailPlanificationMensuelle> DetailPlanificationMensuelle { get; set; }
        public virtual ICollection<JourMois> JourMois { get; set; }
    }
}
