//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARMU.Modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuiviDemande
    {
        public SuiviDemande()
        {
            this.Action = new HashSet<Action>();
        }
    
        public int ID { get; set; }
        public bool VerificationInfrastructure { get; set; }
        public Nullable<int> DureeSurveillance { get; set; }
        public Nullable<System.DateTime> DateAgenda { get; set; }
        public Nullable<int> NbConstatEmis { get; set; }
        public Nullable<int> NbPoliciers { get; set; }
        public bool TypeSurveillance { get; set; }
        public string Commentaires { get; set; }
        public Nullable<bool> Complete { get; set; }
        public bool Retourne { get; set; }
        public string RetourPar { get; set; }
        public Nullable<System.DateTime> RetourDate { get; set; }
        public Nullable<System.DateTime> RetourHeure { get; set; }
        public string RetourMoyen { get; set; }
        public bool Parl { get; set; }
        public string ParlPar { get; set; }
        public string ControlePar { get; set; }
        public int DemandesSpecialesID { get; set; }
        public Nullable<int> PatrouilleurEmployeeID { get; set; }
    
        public virtual ICollection<Action> Action { get; set; }
        public virtual DemandeSpeciale DemandeSpeciale { get; set; }
        public virtual Patrouilleur Patrouilleur { get; set; }
    }
}
