//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARMU.Modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class TacheQuotidienne
    {
        public TacheQuotidienne()
        {
            this.TacheQuotidienne_Assignation = new HashSet<TacheQuotidienne_Assignation>();
            this.DemandeSpeciale = new HashSet<DemandeSpeciale>();
            this.Patrouilleur = new HashSet<Patrouilleur>();
        }
    
        public int ID { get; set; }
        public string SecteurID { get; set; }
        public int JourMoisID { get; set; }
        public string DixVingt { get; set; }
    
        public virtual JourMois JourMois { get; set; }
        public virtual Secteur Secteur { get; set; }
        public virtual ICollection<TacheQuotidienne_Assignation> TacheQuotidienne_Assignation { get; set; }
        public virtual ICollection<DemandeSpeciale> DemandeSpeciale { get; set; }
        public virtual ICollection<Patrouilleur> Patrouilleur { get; set; }
    }
}
