//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARMU.Modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class TacheQuotidienne_Assignation
    {
        public int TacheQuotidienneID { get; set; }
        public int AssignationDetailPlanID { get; set; }
        public int AssignationJourMoisID { get; set; }
        public bool Complete { get; set; }
    
        public virtual Assignation Assignation { get; set; }
        public virtual TacheQuotidienne TacheQuotidienne { get; set; }
    }
}
